window.DESCRIPTIONS = {
  "Portret": [
    "Naturalny portret osoby w jasnym studiu; miękkie poranne światło i autentyczna, niewymuszona atmosfera.",
    "Naturalny portret osoby na miejskiej ulicy; ciepłe światło zachodu i autentyczna, niewymuszona atmosfera.",
    "Naturalny portret osoby w spokojnym parku; subtelne cienie i autentyczna, niewymuszona atmosfera.",
    "Naturalny portret osoby przy dużym oknie; naturalne światło dzienne i autentyczna, niewymuszona atmosfera.",
    "Naturalny portret osoby na tle starej kamienicy; delikatna mgła i autentyczna, niewymuszona atmosfera.",
    "Naturalny portret osoby wśród wysokich traw; kontrastowe światło boczne i autentyczna, niewymuszona atmosfera.",
    "Naturalny portret osoby na schodach; stonowane kolory i autentyczna, niewymuszona atmosfera.",
    "Naturalny portret osoby przy brzegu jeziora; złota godzina i autentyczna, niewymuszona atmosfera.",
    "Naturalny portret osoby w przytulnym wnętrzu; lekko pochmurne niebo i autentyczna, niewymuszona atmosfera.",
    "Naturalny portret osoby pod wieczornym niebem; światło wpadające z boku i autentyczna, niewymuszona atmosfera.",
    "Spokojny portret osoby w jasnym studiu; ciepłe światło zachodu i autentyczna, niewymuszona atmosfera.",
    "Spokojny portret osoby na miejskiej ulicy; subtelne cienie i autentyczna, niewymuszona atmosfera.",
    "Spokojny portret osoby w spokojnym parku; naturalne światło dzienne i autentyczna, niewymuszona atmosfera.",
    "Spokojny portret osoby przy dużym oknie; delikatna mgła i autentyczna, niewymuszona atmosfera.",
    "Spokojny portret osoby na tle starej kamienicy; kontrastowe światło boczne i autentyczna, niewymuszona atmosfera.",
    "Spokojny portret osoby wśród wysokich traw; stonowane kolory i autentyczna, niewymuszona atmosfera.",
    "Spokojny portret osoby na schodach; złota godzina i autentyczna, niewymuszona atmosfera.",
    "Spokojny portret osoby przy brzegu jeziora; lekko pochmurne niebo i autentyczna, niewymuszona atmosfera.",
    "Spokojny portret osoby w przytulnym wnętrzu; światło wpadające z boku i autentyczna, niewymuszona atmosfera.",
    "Spokojny portret osoby pod wieczornym niebem; miękkie poranne światło i autentyczna, niewymuszona atmosfera.",
    "Wyrazisty portret osoby w jasnym studiu; subtelne cienie i autentyczna, niewymuszona atmosfera.",
    "Wyrazisty portret osoby na miejskiej ulicy; naturalne światło dzienne i autentyczna, niewymuszona atmosfera.",
    "Wyrazisty portret osoby w spokojnym parku; delikatna mgła i autentyczna, niewymuszona atmosfera.",
    "Wyrazisty portret osoby przy dużym oknie; kontrastowe światło boczne i autentyczna, niewymuszona atmosfera.",
    "Wyrazisty portret osoby na tle starej kamienicy; stonowane kolory i autentyczna, niewymuszona atmosfera.",
    "Wyrazisty portret osoby wśród wysokich traw; złota godzina i autentyczna, niewymuszona atmosfera.",
    "Wyrazisty portret osoby na schodach; lekko pochmurne niebo i autentyczna, niewymuszona atmosfera.",
    "Wyrazisty portret osoby przy brzegu jeziora; światło wpadające z boku i autentyczna, niewymuszona atmosfera.",
    "Wyrazisty portret osoby w przytulnym wnętrzu; miękkie poranne światło i autentyczna, niewymuszona atmosfera.",
    "Wyrazisty portret osoby pod wieczornym niebem; ciepłe światło zachodu i autentyczna, niewymuszona atmosfera.",
    "Swobodny portret osoby w jasnym studiu; naturalne światło dzienne i autentyczna, niewymuszona atmosfera.",
    "Swobodny portret osoby na miejskiej ulicy; delikatna mgła i autentyczna, niewymuszona atmosfera.",
    "Swobodny portret osoby w spokojnym parku; kontrastowe światło boczne i autentyczna, niewymuszona atmosfera.",
    "Swobodny portret osoby przy dużym oknie; stonowane kolory i autentyczna, niewymuszona atmosfera.",
    "Swobodny portret osoby na tle starej kamienicy; złota godzina i autentyczna, niewymuszona atmosfera.",
    "Swobodny portret osoby wśród wysokich traw; lekko pochmurne niebo i autentyczna, niewymuszona atmosfera.",
    "Swobodny portret osoby na schodach; światło wpadające z boku i autentyczna, niewymuszona atmosfera.",
    "Swobodny portret osoby przy brzegu jeziora; miękkie poranne światło i autentyczna, niewymuszona atmosfera.",
    "Swobodny portret osoby w przytulnym wnętrzu; ciepłe światło zachodu i autentyczna, niewymuszona atmosfera.",
    "Swobodny portret osoby pod wieczornym niebem; subtelne cienie i autentyczna, niewymuszona atmosfera.",
    "Bliski portret osoby w jasnym studiu; delikatna mgła i autentyczna, niewymuszona atmosfera.",
    "Bliski portret osoby na miejskiej ulicy; kontrastowe światło boczne i autentyczna, niewymuszona atmosfera.",
    "Bliski portret osoby w spokojnym parku; stonowane kolory i autentyczna, niewymuszona atmosfera.",
    "Bliski portret osoby przy dużym oknie; złota godzina i autentyczna, niewymuszona atmosfera.",
    "Bliski portret osoby na tle starej kamienicy; lekko pochmurne niebo i autentyczna, niewymuszona atmosfera.",
    "Bliski portret osoby wśród wysokich traw; światło wpadające z boku i autentyczna, niewymuszona atmosfera.",
    "Bliski portret osoby na schodach; miękkie poranne światło i autentyczna, niewymuszona atmosfera.",
    "Bliski portret osoby przy brzegu jeziora; ciepłe światło zachodu i autentyczna, niewymuszona atmosfera.",
    "Bliski portret osoby w przytulnym wnętrzu; subtelne cienie i autentyczna, niewymuszona atmosfera.",
    "Bliski portret osoby pod wieczornym niebem; naturalne światło dzienne i autentyczna, niewymuszona atmosfera.",
    "Filmowy portret osoby w jasnym studiu; kontrastowe światło boczne i autentyczna, niewymuszona atmosfera.",
    "Filmowy portret osoby na miejskiej ulicy; stonowane kolory i autentyczna, niewymuszona atmosfera.",
    "Filmowy portret osoby w spokojnym parku; złota godzina i autentyczna, niewymuszona atmosfera.",
    "Filmowy portret osoby przy dużym oknie; lekko pochmurne niebo i autentyczna, niewymuszona atmosfera.",
    "Filmowy portret osoby na tle starej kamienicy; światło wpadające z boku i autentyczna, niewymuszona atmosfera.",
    "Filmowy portret osoby wśród wysokich traw; miękkie poranne światło i autentyczna, niewymuszona atmosfera.",
    "Filmowy portret osoby na schodach; ciepłe światło zachodu i autentyczna, niewymuszona atmosfera.",
    "Filmowy portret osoby przy brzegu jeziora; subtelne cienie i autentyczna, niewymuszona atmosfera.",
    "Filmowy portret osoby w przytulnym wnętrzu; naturalne światło dzienne i autentyczna, niewymuszona atmosfera.",
    "Filmowy portret osoby pod wieczornym niebem; delikatna mgła i autentyczna, niewymuszona atmosfera.",
    "Minimalistyczny portret osoby w jasnym studiu; stonowane kolory i autentyczna, niewymuszona atmosfera.",
    "Minimalistyczny portret osoby na miejskiej ulicy; złota godzina i autentyczna, niewymuszona atmosfera.",
    "Minimalistyczny portret osoby w spokojnym parku; lekko pochmurne niebo i autentyczna, niewymuszona atmosfera.",
    "Minimalistyczny portret osoby przy dużym oknie; światło wpadające z boku i autentyczna, niewymuszona atmosfera.",
    "Minimalistyczny portret osoby na tle starej kamienicy; miękkie poranne światło i autentyczna, niewymuszona atmosfera.",
    "Minimalistyczny portret osoby wśród wysokich traw; ciepłe światło zachodu i autentyczna, niewymuszona atmosfera.",
    "Minimalistyczny portret osoby na schodach; subtelne cienie i autentyczna, niewymuszona atmosfera.",
    "Minimalistyczny portret osoby przy brzegu jeziora; naturalne światło dzienne i autentyczna, niewymuszona atmosfera.",
    "Minimalistyczny portret osoby w przytulnym wnętrzu; delikatna mgła i autentyczna, niewymuszona atmosfera.",
    "Minimalistyczny portret osoby pod wieczornym niebem; kontrastowe światło boczne i autentyczna, niewymuszona atmosfera.",
    "Ciepły portret osoby w jasnym studiu; złota godzina i autentyczna, niewymuszona atmosfera.",
    "Ciepły portret osoby na miejskiej ulicy; lekko pochmurne niebo i autentyczna, niewymuszona atmosfera.",
    "Ciepły portret osoby w spokojnym parku; światło wpadające z boku i autentyczna, niewymuszona atmosfera.",
    "Ciepły portret osoby przy dużym oknie; miękkie poranne światło i autentyczna, niewymuszona atmosfera.",
    "Ciepły portret osoby na tle starej kamienicy; ciepłe światło zachodu i autentyczna, niewymuszona atmosfera.",
    "Ciepły portret osoby wśród wysokich traw; subtelne cienie i autentyczna, niewymuszona atmosfera.",
    "Ciepły portret osoby na schodach; naturalne światło dzienne i autentyczna, niewymuszona atmosfera.",
    "Ciepły portret osoby przy brzegu jeziora; delikatna mgła i autentyczna, niewymuszona atmosfera.",
    "Ciepły portret osoby w przytulnym wnętrzu; kontrastowe światło boczne i autentyczna, niewymuszona atmosfera.",
    "Ciepły portret osoby pod wieczornym niebem; stonowane kolory i autentyczna, niewymuszona atmosfera.",
    "Nastrojowy portret osoby w jasnym studiu; lekko pochmurne niebo i autentyczna, niewymuszona atmosfera.",
    "Nastrojowy portret osoby na miejskiej ulicy; światło wpadające z boku i autentyczna, niewymuszona atmosfera.",
    "Nastrojowy portret osoby w spokojnym parku; miękkie poranne światło i autentyczna, niewymuszona atmosfera.",
    "Nastrojowy portret osoby przy dużym oknie; ciepłe światło zachodu i autentyczna, niewymuszona atmosfera.",
    "Nastrojowy portret osoby na tle starej kamienicy; subtelne cienie i autentyczna, niewymuszona atmosfera.",
    "Nastrojowy portret osoby wśród wysokich traw; naturalne światło dzienne i autentyczna, niewymuszona atmosfera.",
    "Nastrojowy portret osoby na schodach; delikatna mgła i autentyczna, niewymuszona atmosfera.",
    "Nastrojowy portret osoby przy brzegu jeziora; kontrastowe światło boczne i autentyczna, niewymuszona atmosfera.",
    "Nastrojowy portret osoby w przytulnym wnętrzu; stonowane kolory i autentyczna, niewymuszona atmosfera.",
    "Nastrojowy portret osoby pod wieczornym niebem; złota godzina i autentyczna, niewymuszona atmosfera.",
    "Elegancki portret osoby w jasnym studiu; światło wpadające z boku i autentyczna, niewymuszona atmosfera.",
    "Elegancki portret osoby na miejskiej ulicy; miękkie poranne światło i autentyczna, niewymuszona atmosfera.",
    "Elegancki portret osoby w spokojnym parku; ciepłe światło zachodu i autentyczna, niewymuszona atmosfera.",
    "Elegancki portret osoby przy dużym oknie; subtelne cienie i autentyczna, niewymuszona atmosfera.",
    "Elegancki portret osoby na tle starej kamienicy; naturalne światło dzienne i autentyczna, niewymuszona atmosfera.",
    "Elegancki portret osoby wśród wysokich traw; delikatna mgła i autentyczna, niewymuszona atmosfera.",
    "Elegancki portret osoby na schodach; kontrastowe światło boczne i autentyczna, niewymuszona atmosfera.",
    "Elegancki portret osoby przy brzegu jeziora; stonowane kolory i autentyczna, niewymuszona atmosfera.",
    "Elegancki portret osoby w przytulnym wnętrzu; złota godzina i autentyczna, niewymuszona atmosfera.",
    "Elegancki portret osoby pod wieczornym niebem; lekko pochmurne niebo i autentyczna, niewymuszona atmosfera."
  ],
  "Para": [
    "Para stoi blisko siebie w jasnym studiu; miękkie poranne światło i autentyczna, niewymuszona atmosfera.",
    "Para stoi blisko siebie na miejskiej ulicy; ciepłe światło zachodu i autentyczna, niewymuszona atmosfera.",
    "Para stoi blisko siebie w spokojnym parku; subtelne cienie i autentyczna, niewymuszona atmosfera.",
    "Para stoi blisko siebie przy dużym oknie; naturalne światło dzienne i autentyczna, niewymuszona atmosfera.",
    "Para stoi blisko siebie na tle starej kamienicy; delikatna mgła i autentyczna, niewymuszona atmosfera.",
    "Para stoi blisko siebie wśród wysokich traw; kontrastowe światło boczne i autentyczna, niewymuszona atmosfera.",
    "Para stoi blisko siebie na schodach; stonowane kolory i autentyczna, niewymuszona atmosfera.",
    "Para stoi blisko siebie przy brzegu jeziora; złota godzina i autentyczna, niewymuszona atmosfera.",
    "Para stoi blisko siebie w przytulnym wnętrzu; lekko pochmurne niebo i autentyczna, niewymuszona atmosfera.",
    "Para stoi blisko siebie pod wieczornym niebem; światło wpadające z boku i autentyczna, niewymuszona atmosfera.",
    "Para idzie razem w jasnym studiu; ciepłe światło zachodu i autentyczna, niewymuszona atmosfera.",
    "Para idzie razem na miejskiej ulicy; subtelne cienie i autentyczna, niewymuszona atmosfera.",
    "Para idzie razem w spokojnym parku; naturalne światło dzienne i autentyczna, niewymuszona atmosfera.",
    "Para idzie razem przy dużym oknie; delikatna mgła i autentyczna, niewymuszona atmosfera.",
    "Para idzie razem na tle starej kamienicy; kontrastowe światło boczne i autentyczna, niewymuszona atmosfera.",
    "Para idzie razem wśród wysokich traw; stonowane kolory i autentyczna, niewymuszona atmosfera.",
    "Para idzie razem na schodach; złota godzina i autentyczna, niewymuszona atmosfera.",
    "Para idzie razem przy brzegu jeziora; lekko pochmurne niebo i autentyczna, niewymuszona atmosfera.",
    "Para idzie razem w przytulnym wnętrzu; światło wpadające z boku i autentyczna, niewymuszona atmosfera.",
    "Para idzie razem pod wieczornym niebem; miękkie poranne światło i autentyczna, niewymuszona atmosfera.",
    "Para śmieje się do siebie w jasnym studiu; subtelne cienie i autentyczna, niewymuszona atmosfera.",
    "Para śmieje się do siebie na miejskiej ulicy; naturalne światło dzienne i autentyczna, niewymuszona atmosfera.",
    "Para śmieje się do siebie w spokojnym parku; delikatna mgła i autentyczna, niewymuszona atmosfera.",
    "Para śmieje się do siebie przy dużym oknie; kontrastowe światło boczne i autentyczna, niewymuszona atmosfera.",
    "Para śmieje się do siebie na tle starej kamienicy; stonowane kolory i autentyczna, niewymuszona atmosfera.",
    "Para śmieje się do siebie wśród wysokich traw; złota godzina i autentyczna, niewymuszona atmosfera.",
    "Para śmieje się do siebie na schodach; lekko pochmurne niebo i autentyczna, niewymuszona atmosfera.",
    "Para śmieje się do siebie przy brzegu jeziora; światło wpadające z boku i autentyczna, niewymuszona atmosfera.",
    "Para śmieje się do siebie w przytulnym wnętrzu; miękkie poranne światło i autentyczna, niewymuszona atmosfera.",
    "Para śmieje się do siebie pod wieczornym niebem; ciepłe światło zachodu i autentyczna, niewymuszona atmosfera.",
    "Para obejmuje się w jasnym studiu; naturalne światło dzienne i autentyczna, niewymuszona atmosfera.",
    "Para obejmuje się na miejskiej ulicy; delikatna mgła i autentyczna, niewymuszona atmosfera.",
    "Para obejmuje się w spokojnym parku; kontrastowe światło boczne i autentyczna, niewymuszona atmosfera.",
    "Para obejmuje się przy dużym oknie; stonowane kolory i autentyczna, niewymuszona atmosfera.",
    "Para obejmuje się na tle starej kamienicy; złota godzina i autentyczna, niewymuszona atmosfera.",
    "Para obejmuje się wśród wysokich traw; lekko pochmurne niebo i autentyczna, niewymuszona atmosfera.",
    "Para obejmuje się na schodach; światło wpadające z boku i autentyczna, niewymuszona atmosfera.",
    "Para obejmuje się przy brzegu jeziora; miękkie poranne światło i autentyczna, niewymuszona atmosfera.",
    "Para obejmuje się w przytulnym wnętrzu; ciepłe światło zachodu i autentyczna, niewymuszona atmosfera.",
    "Para obejmuje się pod wieczornym niebem; subtelne cienie i autentyczna, niewymuszona atmosfera.",
    "Para siedzi obok siebie w jasnym studiu; delikatna mgła i autentyczna, niewymuszona atmosfera.",
    "Para siedzi obok siebie na miejskiej ulicy; kontrastowe światło boczne i autentyczna, niewymuszona atmosfera.",
    "Para siedzi obok siebie w spokojnym parku; stonowane kolory i autentyczna, niewymuszona atmosfera.",
    "Para siedzi obok siebie przy dużym oknie; złota godzina i autentyczna, niewymuszona atmosfera.",
    "Para siedzi obok siebie na tle starej kamienicy; lekko pochmurne niebo i autentyczna, niewymuszona atmosfera.",
    "Para siedzi obok siebie wśród wysokich traw; światło wpadające z boku i autentyczna, niewymuszona atmosfera.",
    "Para siedzi obok siebie na schodach; miękkie poranne światło i autentyczna, niewymuszona atmosfera.",
    "Para siedzi obok siebie przy brzegu jeziora; ciepłe światło zachodu i autentyczna, niewymuszona atmosfera.",
    "Para siedzi obok siebie w przytulnym wnętrzu; subtelne cienie i autentyczna, niewymuszona atmosfera.",
    "Para siedzi obok siebie pod wieczornym niebem; naturalne światło dzienne i autentyczna, niewymuszona atmosfera.",
    "Para patrzy sobie w oczy w jasnym studiu; kontrastowe światło boczne i autentyczna, niewymuszona atmosfera.",
    "Para patrzy sobie w oczy na miejskiej ulicy; stonowane kolory i autentyczna, niewymuszona atmosfera.",
    "Para patrzy sobie w oczy w spokojnym parku; złota godzina i autentyczna, niewymuszona atmosfera.",
    "Para patrzy sobie w oczy przy dużym oknie; lekko pochmurne niebo i autentyczna, niewymuszona atmosfera.",
    "Para patrzy sobie w oczy na tle starej kamienicy; światło wpadające z boku i autentyczna, niewymuszona atmosfera.",
    "Para patrzy sobie w oczy wśród wysokich traw; miękkie poranne światło i autentyczna, niewymuszona atmosfera.",
    "Para patrzy sobie w oczy na schodach; ciepłe światło zachodu i autentyczna, niewymuszona atmosfera.",
    "Para patrzy sobie w oczy przy brzegu jeziora; subtelne cienie i autentyczna, niewymuszona atmosfera.",
    "Para patrzy sobie w oczy w przytulnym wnętrzu; naturalne światło dzienne i autentyczna, niewymuszona atmosfera.",
    "Para patrzy sobie w oczy pod wieczornym niebem; delikatna mgła i autentyczna, niewymuszona atmosfera.",
    "Para trzyma się za ręce w jasnym studiu; stonowane kolory i autentyczna, niewymuszona atmosfera.",
    "Para trzyma się za ręce na miejskiej ulicy; złota godzina i autentyczna, niewymuszona atmosfera.",
    "Para trzyma się za ręce w spokojnym parku; lekko pochmurne niebo i autentyczna, niewymuszona atmosfera.",
    "Para trzyma się za ręce przy dużym oknie; światło wpadające z boku i autentyczna, niewymuszona atmosfera.",
    "Para trzyma się za ręce na tle starej kamienicy; miękkie poranne światło i autentyczna, niewymuszona atmosfera.",
    "Para trzyma się za ręce wśród wysokich traw; ciepłe światło zachodu i autentyczna, niewymuszona atmosfera.",
    "Para trzyma się za ręce na schodach; subtelne cienie i autentyczna, niewymuszona atmosfera.",
    "Para trzyma się za ręce przy brzegu jeziora; naturalne światło dzienne i autentyczna, niewymuszona atmosfera.",
    "Para trzyma się za ręce w przytulnym wnętrzu; delikatna mgła i autentyczna, niewymuszona atmosfera.",
    "Para trzyma się za ręce pod wieczornym niebem; kontrastowe światło boczne i autentyczna, niewymuszona atmosfera.",
    "Para opiera się o siebie w jasnym studiu; złota godzina i autentyczna, niewymuszona atmosfera.",
    "Para opiera się o siebie na miejskiej ulicy; lekko pochmurne niebo i autentyczna, niewymuszona atmosfera.",
    "Para opiera się o siebie w spokojnym parku; światło wpadające z boku i autentyczna, niewymuszona atmosfera.",
    "Para opiera się o siebie przy dużym oknie; miękkie poranne światło i autentyczna, niewymuszona atmosfera.",
    "Para opiera się o siebie na tle starej kamienicy; ciepłe światło zachodu i autentyczna, niewymuszona atmosfera.",
    "Para opiera się o siebie wśród wysokich traw; subtelne cienie i autentyczna, niewymuszona atmosfera.",
    "Para opiera się o siebie na schodach; naturalne światło dzienne i autentyczna, niewymuszona atmosfera.",
    "Para opiera się o siebie przy brzegu jeziora; delikatna mgła i autentyczna, niewymuszona atmosfera.",
    "Para opiera się o siebie w przytulnym wnętrzu; kontrastowe światło boczne i autentyczna, niewymuszona atmosfera.",
    "Para opiera się o siebie pod wieczornym niebem; stonowane kolory i autentyczna, niewymuszona atmosfera.",
    "Para tańczy powoli w jasnym studiu; lekko pochmurne niebo i autentyczna, niewymuszona atmosfera.",
    "Para tańczy powoli na miejskiej ulicy; światło wpadające z boku i autentyczna, niewymuszona atmosfera.",
    "Para tańczy powoli w spokojnym parku; miękkie poranne światło i autentyczna, niewymuszona atmosfera.",
    "Para tańczy powoli przy dużym oknie; ciepłe światło zachodu i autentyczna, niewymuszona atmosfera.",
    "Para tańczy powoli na tle starej kamienicy; subtelne cienie i autentyczna, niewymuszona atmosfera.",
    "Para tańczy powoli wśród wysokich traw; naturalne światło dzienne i autentyczna, niewymuszona atmosfera.",
    "Para tańczy powoli na schodach; delikatna mgła i autentyczna, niewymuszona atmosfera.",
    "Para tańczy powoli przy brzegu jeziora; kontrastowe światło boczne i autentyczna, niewymuszona atmosfera.",
    "Para tańczy powoli w przytulnym wnętrzu; stonowane kolory i autentyczna, niewymuszona atmosfera.",
    "Para tańczy powoli pod wieczornym niebem; złota godzina i autentyczna, niewymuszona atmosfera.",
    "Para odpoczywa razem w jasnym studiu; światło wpadające z boku i autentyczna, niewymuszona atmosfera.",
    "Para odpoczywa razem na miejskiej ulicy; miękkie poranne światło i autentyczna, niewymuszona atmosfera.",
    "Para odpoczywa razem w spokojnym parku; ciepłe światło zachodu i autentyczna, niewymuszona atmosfera.",
    "Para odpoczywa razem przy dużym oknie; subtelne cienie i autentyczna, niewymuszona atmosfera.",
    "Para odpoczywa razem na tle starej kamienicy; naturalne światło dzienne i autentyczna, niewymuszona atmosfera.",
    "Para odpoczywa razem wśród wysokich traw; delikatna mgła i autentyczna, niewymuszona atmosfera.",
    "Para odpoczywa razem na schodach; kontrastowe światło boczne i autentyczna, niewymuszona atmosfera.",
    "Para odpoczywa razem przy brzegu jeziora; stonowane kolory i autentyczna, niewymuszona atmosfera.",
    "Para odpoczywa razem w przytulnym wnętrzu; złota godzina i autentyczna, niewymuszona atmosfera.",
    "Para odpoczywa razem pod wieczornym niebem; lekko pochmurne niebo i autentyczna, niewymuszona atmosfera."
  ],
  "Rodzina": [
    "Rodzina spędza wspólną chwilę w jasnym studiu; miękkie poranne światło i autentyczna, niewymuszona atmosfera.",
    "Rodzina spędza wspólną chwilę na miejskiej ulicy; ciepłe światło zachodu i autentyczna, niewymuszona atmosfera.",
    "Rodzina spędza wspólną chwilę w spokojnym parku; subtelne cienie i autentyczna, niewymuszona atmosfera.",
    "Rodzina spędza wspólną chwilę przy dużym oknie; naturalne światło dzienne i autentyczna, niewymuszona atmosfera.",
    "Rodzina spędza wspólną chwilę na tle starej kamienicy; delikatna mgła i autentyczna, niewymuszona atmosfera.",
    "Rodzina spędza wspólną chwilę wśród wysokich traw; kontrastowe światło boczne i autentyczna, niewymuszona atmosfera.",
    "Rodzina spędza wspólną chwilę na schodach; stonowane kolory i autentyczna, niewymuszona atmosfera.",
    "Rodzina spędza wspólną chwilę przy brzegu jeziora; złota godzina i autentyczna, niewymuszona atmosfera.",
    "Rodzina spędza wspólną chwilę w przytulnym wnętrzu; lekko pochmurne niebo i autentyczna, niewymuszona atmosfera.",
    "Rodzina spędza wspólną chwilę pod wieczornym niebem; światło wpadające z boku i autentyczna, niewymuszona atmosfera.",
    "Rodzina spaceruje razem w jasnym studiu; ciepłe światło zachodu i autentyczna, niewymuszona atmosfera.",
    "Rodzina spaceruje razem na miejskiej ulicy; subtelne cienie i autentyczna, niewymuszona atmosfera.",
    "Rodzina spaceruje razem w spokojnym parku; naturalne światło dzienne i autentyczna, niewymuszona atmosfera.",
    "Rodzina spaceruje razem przy dużym oknie; delikatna mgła i autentyczna, niewymuszona atmosfera.",
    "Rodzina spaceruje razem na tle starej kamienicy; kontrastowe światło boczne i autentyczna, niewymuszona atmosfera.",
    "Rodzina spaceruje razem wśród wysokich traw; stonowane kolory i autentyczna, niewymuszona atmosfera.",
    "Rodzina spaceruje razem na schodach; złota godzina i autentyczna, niewymuszona atmosfera.",
    "Rodzina spaceruje razem przy brzegu jeziora; lekko pochmurne niebo i autentyczna, niewymuszona atmosfera.",
    "Rodzina spaceruje razem w przytulnym wnętrzu; światło wpadające z boku i autentyczna, niewymuszona atmosfera.",
    "Rodzina spaceruje razem pod wieczornym niebem; miękkie poranne światło i autentyczna, niewymuszona atmosfera.",
    "Rodzina siedzi blisko siebie w jasnym studiu; subtelne cienie i autentyczna, niewymuszona atmosfera.",
    "Rodzina siedzi blisko siebie na miejskiej ulicy; naturalne światło dzienne i autentyczna, niewymuszona atmosfera.",
    "Rodzina siedzi blisko siebie w spokojnym parku; delikatna mgła i autentyczna, niewymuszona atmosfera.",
    "Rodzina siedzi blisko siebie przy dużym oknie; kontrastowe światło boczne i autentyczna, niewymuszona atmosfera.",
    "Rodzina siedzi blisko siebie na tle starej kamienicy; stonowane kolory i autentyczna, niewymuszona atmosfera.",
    "Rodzina siedzi blisko siebie wśród wysokich traw; złota godzina i autentyczna, niewymuszona atmosfera.",
    "Rodzina siedzi blisko siebie na schodach; lekko pochmurne niebo i autentyczna, niewymuszona atmosfera.",
    "Rodzina siedzi blisko siebie przy brzegu jeziora; światło wpadające z boku i autentyczna, niewymuszona atmosfera.",
    "Rodzina siedzi blisko siebie w przytulnym wnętrzu; miękkie poranne światło i autentyczna, niewymuszona atmosfera.",
    "Rodzina siedzi blisko siebie pod wieczornym niebem; ciepłe światło zachodu i autentyczna, niewymuszona atmosfera.",
    "Rodzina śmieje się razem w jasnym studiu; naturalne światło dzienne i autentyczna, niewymuszona atmosfera.",
    "Rodzina śmieje się razem na miejskiej ulicy; delikatna mgła i autentyczna, niewymuszona atmosfera.",
    "Rodzina śmieje się razem w spokojnym parku; kontrastowe światło boczne i autentyczna, niewymuszona atmosfera.",
    "Rodzina śmieje się razem przy dużym oknie; stonowane kolory i autentyczna, niewymuszona atmosfera.",
    "Rodzina śmieje się razem na tle starej kamienicy; złota godzina i autentyczna, niewymuszona atmosfera.",
    "Rodzina śmieje się razem wśród wysokich traw; lekko pochmurne niebo i autentyczna, niewymuszona atmosfera.",
    "Rodzina śmieje się razem na schodach; światło wpadające z boku i autentyczna, niewymuszona atmosfera.",
    "Rodzina śmieje się razem przy brzegu jeziora; miękkie poranne światło i autentyczna, niewymuszona atmosfera.",
    "Rodzina śmieje się razem w przytulnym wnętrzu; ciepłe światło zachodu i autentyczna, niewymuszona atmosfera.",
    "Rodzina śmieje się razem pod wieczornym niebem; subtelne cienie i autentyczna, niewymuszona atmosfera.",
    "Rodzina przytula się w jasnym studiu; delikatna mgła i autentyczna, niewymuszona atmosfera.",
    "Rodzina przytula się na miejskiej ulicy; kontrastowe światło boczne i autentyczna, niewymuszona atmosfera.",
    "Rodzina przytula się w spokojnym parku; stonowane kolory i autentyczna, niewymuszona atmosfera.",
    "Rodzina przytula się przy dużym oknie; złota godzina i autentyczna, niewymuszona atmosfera.",
    "Rodzina przytula się na tle starej kamienicy; lekko pochmurne niebo i autentyczna, niewymuszona atmosfera.",
    "Rodzina przytula się wśród wysokich traw; światło wpadające z boku i autentyczna, niewymuszona atmosfera.",
    "Rodzina przytula się na schodach; miękkie poranne światło i autentyczna, niewymuszona atmosfera.",
    "Rodzina przytula się przy brzegu jeziora; ciepłe światło zachodu i autentyczna, niewymuszona atmosfera.",
    "Rodzina przytula się w przytulnym wnętrzu; subtelne cienie i autentyczna, niewymuszona atmosfera.",
    "Rodzina przytula się pod wieczornym niebem; naturalne światło dzienne i autentyczna, niewymuszona atmosfera.",
    "Rodzina bawi się razem w jasnym studiu; kontrastowe światło boczne i autentyczna, niewymuszona atmosfera.",
    "Rodzina bawi się razem na miejskiej ulicy; stonowane kolory i autentyczna, niewymuszona atmosfera.",
    "Rodzina bawi się razem w spokojnym parku; złota godzina i autentyczna, niewymuszona atmosfera.",
    "Rodzina bawi się razem przy dużym oknie; lekko pochmurne niebo i autentyczna, niewymuszona atmosfera.",
    "Rodzina bawi się razem na tle starej kamienicy; światło wpadające z boku i autentyczna, niewymuszona atmosfera.",
    "Rodzina bawi się razem wśród wysokich traw; miękkie poranne światło i autentyczna, niewymuszona atmosfera.",
    "Rodzina bawi się razem na schodach; ciepłe światło zachodu i autentyczna, niewymuszona atmosfera.",
    "Rodzina bawi się razem przy brzegu jeziora; subtelne cienie i autentyczna, niewymuszona atmosfera.",
    "Rodzina bawi się razem w przytulnym wnętrzu; naturalne światło dzienne i autentyczna, niewymuszona atmosfera.",
    "Rodzina bawi się razem pod wieczornym niebem; delikatna mgła i autentyczna, niewymuszona atmosfera.",
    "Rodzina rozmawia swobodnie w jasnym studiu; stonowane kolory i autentyczna, niewymuszona atmosfera.",
    "Rodzina rozmawia swobodnie na miejskiej ulicy; złota godzina i autentyczna, niewymuszona atmosfera.",
    "Rodzina rozmawia swobodnie w spokojnym parku; lekko pochmurne niebo i autentyczna, niewymuszona atmosfera.",
    "Rodzina rozmawia swobodnie przy dużym oknie; światło wpadające z boku i autentyczna, niewymuszona atmosfera.",
    "Rodzina rozmawia swobodnie na tle starej kamienicy; miękkie poranne światło i autentyczna, niewymuszona atmosfera.",
    "Rodzina rozmawia swobodnie wśród wysokich traw; ciepłe światło zachodu i autentyczna, niewymuszona atmosfera.",
    "Rodzina rozmawia swobodnie na schodach; subtelne cienie i autentyczna, niewymuszona atmosfera.",
    "Rodzina rozmawia swobodnie przy brzegu jeziora; naturalne światło dzienne i autentyczna, niewymuszona atmosfera.",
    "Rodzina rozmawia swobodnie w przytulnym wnętrzu; delikatna mgła i autentyczna, niewymuszona atmosfera.",
    "Rodzina rozmawia swobodnie pod wieczornym niebem; kontrastowe światło boczne i autentyczna, niewymuszona atmosfera.",
    "Rodzina odpoczywa razem w jasnym studiu; złota godzina i autentyczna, niewymuszona atmosfera.",
    "Rodzina odpoczywa razem na miejskiej ulicy; lekko pochmurne niebo i autentyczna, niewymuszona atmosfera.",
    "Rodzina odpoczywa razem w spokojnym parku; światło wpadające z boku i autentyczna, niewymuszona atmosfera.",
    "Rodzina odpoczywa razem przy dużym oknie; miękkie poranne światło i autentyczna, niewymuszona atmosfera.",
    "Rodzina odpoczywa razem na tle starej kamienicy; ciepłe światło zachodu i autentyczna, niewymuszona atmosfera.",
    "Rodzina odpoczywa razem wśród wysokich traw; subtelne cienie i autentyczna, niewymuszona atmosfera.",
    "Rodzina odpoczywa razem na schodach; naturalne światło dzienne i autentyczna, niewymuszona atmosfera.",
    "Rodzina odpoczywa razem przy brzegu jeziora; delikatna mgła i autentyczna, niewymuszona atmosfera.",
    "Rodzina odpoczywa razem w przytulnym wnętrzu; kontrastowe światło boczne i autentyczna, niewymuszona atmosfera.",
    "Rodzina odpoczywa razem pod wieczornym niebem; stonowane kolory i autentyczna, niewymuszona atmosfera.",
    "Rodzina trzyma się za ręce w jasnym studiu; lekko pochmurne niebo i autentyczna, niewymuszona atmosfera.",
    "Rodzina trzyma się za ręce na miejskiej ulicy; światło wpadające z boku i autentyczna, niewymuszona atmosfera.",
    "Rodzina trzyma się za ręce w spokojnym parku; miękkie poranne światło i autentyczna, niewymuszona atmosfera.",
    "Rodzina trzyma się za ręce przy dużym oknie; ciepłe światło zachodu i autentyczna, niewymuszona atmosfera.",
    "Rodzina trzyma się za ręce na tle starej kamienicy; subtelne cienie i autentyczna, niewymuszona atmosfera.",
    "Rodzina trzyma się za ręce wśród wysokich traw; naturalne światło dzienne i autentyczna, niewymuszona atmosfera.",
    "Rodzina trzyma się za ręce na schodach; delikatna mgła i autentyczna, niewymuszona atmosfera.",
    "Rodzina trzyma się za ręce przy brzegu jeziora; kontrastowe światło boczne i autentyczna, niewymuszona atmosfera.",
    "Rodzina trzyma się za ręce w przytulnym wnętrzu; stonowane kolory i autentyczna, niewymuszona atmosfera.",
    "Rodzina trzyma się za ręce pod wieczornym niebem; złota godzina i autentyczna, niewymuszona atmosfera.",
    "Rodzina patrzy w stronę aparatu w jasnym studiu; światło wpadające z boku i autentyczna, niewymuszona atmosfera.",
    "Rodzina patrzy w stronę aparatu na miejskiej ulicy; miękkie poranne światło i autentyczna, niewymuszona atmosfera.",
    "Rodzina patrzy w stronę aparatu w spokojnym parku; ciepłe światło zachodu i autentyczna, niewymuszona atmosfera.",
    "Rodzina patrzy w stronę aparatu przy dużym oknie; subtelne cienie i autentyczna, niewymuszona atmosfera.",
    "Rodzina patrzy w stronę aparatu na tle starej kamienicy; naturalne światło dzienne i autentyczna, niewymuszona atmosfera.",
    "Rodzina patrzy w stronę aparatu wśród wysokich traw; delikatna mgła i autentyczna, niewymuszona atmosfera.",
    "Rodzina patrzy w stronę aparatu na schodach; kontrastowe światło boczne i autentyczna, niewymuszona atmosfera.",
    "Rodzina patrzy w stronę aparatu przy brzegu jeziora; stonowane kolory i autentyczna, niewymuszona atmosfera.",
    "Rodzina patrzy w stronę aparatu w przytulnym wnętrzu; złota godzina i autentyczna, niewymuszona atmosfera.",
    "Rodzina patrzy w stronę aparatu pod wieczornym niebem; lekko pochmurne niebo i autentyczna, niewymuszona atmosfera."
  ]
};
